import {
    Pagination,
    PagedResult,
    applyPagination,
    applySorting,
    PropertyAccessor,
    SortDirection,
} from '@equinor/fusion';

export type DataItem = {
    id: number;
    firstName: string;
    lastName: string;
    email: string;
    gender: string;
};

const data: DataItem[] = [
    {
        id: 1,
        firstName: 'Jayson',
        lastName: 'Jenckes',
        email: 'jjenckes0@ucsd.edu',
        gender: 'Male',
    },
    {
        id: 2,
        firstName: 'Clemmy',
        lastName: 'Braunter',
        email: 'cbraunter1@fotki.com',
        gender: 'Female',
    },
    {
        id: 3,
        firstName: 'Kimmie',
        lastName: 'McGuffog',
        email: 'kmcguffog2@nsw.gov.au',
        gender: 'Female',
    },
    {
        id: 4,
        firstName: 'Freeman',
        lastName: 'Plumer',
        email: 'fplumer3@earthlink.net',
        gender: 'Male',
    },
    {
        id: 5,
        firstName: 'Ettie',
        lastName: 'MacGeffen',
        email: 'emacgeffen4@gizmodo.com',
        gender: 'Female',
    },
    {
        id: 6,
        firstName: 'Holly',
        lastName: 'Bloomfield',
        email: 'hbloomfield5@infoseek.co.jp',
        gender: 'Female',
    },
    {
        id: 7,
        firstName: 'Doro',
        lastName: 'Sterry',
        email: 'dsterry6@jiathis.com',
        gender: 'Female',
    },
    {
        id: 8,
        firstName: 'Lenka',
        lastName: 'Corck',
        email: 'lcorck7@cdbaby.com',
        gender: 'Female',
    },
    {
        id: 9,
        firstName: 'Haily',
        lastName: 'Blazewicz',
        email: 'hblazewicz8@livejournal.com',
        gender: 'Male',
    },
    {
        id: 10,
        firstName: 'Nicolle',
        lastName: 'Duerden',
        email: 'nduerden9@army.mil',
        gender: 'Female',
    },
    {
        id: 11,
        firstName: 'Shaun',
        lastName: 'Siberry',
        email: 'ssiberrya@tripadvisor.com',
        gender: 'Male',
    },
    {
        id: 12,
        firstName: 'Sarette',
        lastName: 'Stango',
        email: 'sstangob@csmonitor.com',
        gender: 'Female',
    },
    {
        id: 13,
        firstName: 'Francesco',
        lastName: "O'Hare",
        email: 'foharec@cam.ac.uk',
        gender: 'Male',
    },
    {
        id: 14,
        firstName: 'Celina',
        lastName: 'Westrip',
        email: 'cwestripd@pbs.org',
        gender: 'Female',
    },
    {
        id: 15,
        firstName: 'Wilfred',
        lastName: 'Mechan',
        email: 'wmechane@amazon.com',
        gender: 'Male',
    },
    {
        id: 16,
        firstName: 'Bethena',
        lastName: 'Mousby',
        email: 'bmousbyf@cnbc.com',
        gender: 'Female',
    },
    {
        id: 17,
        firstName: 'Jodi',
        lastName: 'Playden',
        email: 'jplaydeng@twitter.com',
        gender: 'Female',
    },
    {
        id: 18,
        firstName: 'Davon',
        lastName: 'Gianni',
        email: 'dgiannih@linkedin.com',
        gender: 'Male',
    },
    {
        id: 19,
        firstName: 'Ashton',
        lastName: 'Bottrill',
        email: 'abottrilli@usa.gov',
        gender: 'Male',
    },
    {
        id: 20,
        firstName: 'Hurlee',
        lastName: 'Simionescu',
        email: 'hsimionescuj@slashdot.org',
        gender: 'Male',
    },
    {
        id: 21,
        firstName: 'Delaney',
        lastName: 'Dunnion',
        email: 'ddunnionk@unc.edu',
        gender: 'Male',
    },
    {
        id: 22,
        firstName: 'Ilysa',
        lastName: 'Lettice',
        email: 'iletticel@netlog.com',
        gender: 'Female',
    },
    {
        id: 23,
        firstName: 'Mollee',
        lastName: 'Bullan',
        email: 'mbullanm@creativecommons.org',
        gender: 'Female',
    },
    {
        id: 24,
        firstName: 'Lowe',
        lastName: 'Mattson',
        email: 'lmattsonn@yandex.ru',
        gender: 'Male',
    },
    {
        id: 25,
        firstName: 'Novelia',
        lastName: 'Stuffins',
        email: 'nstuffinso@miitbeian.gov.cn',
        gender: 'Female',
    },
    {
        id: 26,
        firstName: 'Garnet',
        lastName: 'Hatfull',
        email: 'ghatfullp@goo.ne.jp',
        gender: 'Female',
    },
    {
        id: 27,
        firstName: 'Raoul',
        lastName: 'Mattaser',
        email: 'rmattaserq@chronoengine.com',
        gender: 'Male',
    },
    {
        id: 28,
        firstName: 'Loutitia',
        lastName: 'Abbatucci',
        email: 'labbatuccir@spotify.com',
        gender: 'Female',
    },
    {
        id: 29,
        firstName: 'Emmalyn',
        lastName: 'Dale',
        email: 'edales@constantcontact.com',
        gender: 'Female',
    },
    {
        id: 30,
        firstName: 'Demeter',
        lastName: 'Dolby',
        email: 'ddolbyt@wiley.com',
        gender: 'Female',
    },
    {
        id: 31,
        firstName: 'Dania',
        lastName: 'Izakov',
        email: 'dizakovu@bravesites.com',
        gender: 'Female',
    },
    {
        id: 32,
        firstName: 'Sax',
        lastName: 'Doerr',
        email: 'sdoerrv@arizona.edu',
        gender: 'Male',
    },
    {
        id: 33,
        firstName: 'Robbert',
        lastName: 'Bugdall',
        email: 'rbugdallw@narod.ru',
        gender: 'Male',
    },
    {
        id: 34,
        firstName: 'Car',
        lastName: 'Kersey',
        email: 'ckerseyx@i2i.jp',
        gender: 'Male',
    },
    {
        id: 35,
        firstName: 'Letitia',
        lastName: 'Cumberpatch',
        email: 'lcumberpatchy@buzzfeed.com',
        gender: 'Female',
    },
    {
        id: 36,
        firstName: 'Thaine',
        lastName: 'Dunseath',
        email: 'tdunseathz@behance.net',
        gender: 'Male',
    },
    {
        id: 37,
        firstName: 'Pincus',
        lastName: 'Ciccetti',
        email: 'pciccetti10@cisco.com',
        gender: 'Male',
    },
    {
        id: 38,
        firstName: 'Robinett',
        lastName: 'Plummer',
        email: 'rplummer11@independent.co.uk',
        gender: 'Female',
    },
    {
        id: 39,
        firstName: 'Isiahi',
        lastName: "O'Hallagan",
        email: 'iohallagan12@virginia.edu',
        gender: 'Male',
    },
    {
        id: 40,
        firstName: 'Jonathon',
        lastName: 'Banister',
        email: 'jbanister13@rediff.com',
        gender: 'Male',
    },
    {
        id: 41,
        firstName: 'Gussy',
        lastName: 'Dovermann',
        email: 'gdovermann14@xing.com',
        gender: 'Female',
    },
    {
        id: 42,
        firstName: 'Jay',
        lastName: 'Parkhouse',
        email: 'jparkhouse15@nba.com',
        gender: 'Male',
    },
    {
        id: 43,
        firstName: 'Herc',
        lastName: 'Prangle',
        email: 'hprangle16@macromedia.com',
        gender: 'Male',
    },
    {
        id: 44,
        firstName: 'Jaye',
        lastName: 'Plowes',
        email: 'jplowes17@e-recht24.de',
        gender: 'Male',
    },
    {
        id: 45,
        firstName: 'Chevy',
        lastName: 'Abba',
        email: 'cabba18@ucoz.ru',
        gender: 'Male',
    },
    {
        id: 46,
        firstName: 'Brennen',
        lastName: 'Badby',
        email: 'bbadby19@yellowpages.com',
        gender: 'Male',
    },
    {
        id: 47,
        firstName: 'Trixie',
        lastName: 'Dungey',
        email: 'tdungey1a@umich.edu',
        gender: 'Female',
    },
    {
        id: 48,
        firstName: 'Udall',
        lastName: 'Ironside',
        email: 'uironside1b@gnu.org',
        gender: 'Male',
    },
    {
        id: 49,
        firstName: 'Demetra',
        lastName: 'Worrall',
        email: 'dworrall1c@alibaba.com',
        gender: 'Female',
    },
    {
        id: 50,
        firstName: 'Lenard',
        lastName: 'Tavinor',
        email: 'ltavinor1d@washington.edu',
        gender: 'Male',
    },
    {
        id: 51,
        firstName: 'Ellissa',
        lastName: 'Toll',
        email: 'etoll1e@abc.net.au',
        gender: 'Female',
    },
    {
        id: 52,
        firstName: 'Bernie',
        lastName: 'Varnals',
        email: 'bvarnals1f@boston.com',
        gender: 'Male',
    },
    {
        id: 53,
        firstName: 'Collin',
        lastName: 'Brymner',
        email: 'cbrymner1g@sun.com',
        gender: 'Male',
    },
    {
        id: 54,
        firstName: 'Cory',
        lastName: 'Origan',
        email: 'corigan1h@symantec.com',
        gender: 'Male',
    },
    {
        id: 55,
        firstName: 'Willis',
        lastName: 'Flay',
        email: 'wflay1i@examiner.com',
        gender: 'Male',
    },
    {
        id: 56,
        firstName: 'Margaretta',
        lastName: 'Nenci',
        email: 'mnenci1j@alexa.com',
        gender: 'Female',
    },
    {
        id: 57,
        firstName: 'Rafaela',
        lastName: 'Van Arsdale',
        email: 'rvanarsdale1k@amazon.com',
        gender: 'Female',
    },
    {
        id: 58,
        firstName: 'Adey',
        lastName: 'Tunnadine',
        email: 'atunnadine1l@ebay.co.uk',
        gender: 'Female',
    },
    {
        id: 59,
        firstName: 'Neely',
        lastName: 'Moro',
        email: 'nmoro1m@examiner.com',
        gender: 'Female',
    },
    {
        id: 60,
        firstName: 'Maxy',
        lastName: 'McFarland',
        email: 'mmcfarland1n@noaa.gov',
        gender: 'Male',
    },
    {
        id: 61,
        firstName: 'Isadore',
        lastName: 'Hawe',
        email: 'ihawe1o@google.com.hk',
        gender: 'Male',
    },
    {
        id: 62,
        firstName: 'Burty',
        lastName: 'Chellam',
        email: 'bchellam1p@ftc.gov',
        gender: 'Male',
    },
    {
        id: 63,
        firstName: 'Phip',
        lastName: 'Bickley',
        email: 'pbickley1q@opera.com',
        gender: 'Male',
    },
    {
        id: 64,
        firstName: 'Wendy',
        lastName: 'Sikora',
        email: 'wsikora1r@360.cn',
        gender: 'Female',
    },
    {
        id: 65,
        firstName: 'Peterus',
        lastName: 'Kemmish',
        email: 'pkemmish1s@yandex.ru',
        gender: 'Male',
    },
    {
        id: 66,
        firstName: 'Valeda',
        lastName: 'Mackrill',
        email: 'vmackrill1t@flavors.me',
        gender: 'Female',
    },
    {
        id: 67,
        firstName: 'Nedi',
        lastName: 'Heeron',
        email: 'nheeron1u@discuz.net',
        gender: 'Female',
    },
    {
        id: 68,
        firstName: 'Allin',
        lastName: 'Dundendale',
        email: 'adundendale1v@usa.gov',
        gender: 'Male',
    },
    {
        id: 69,
        firstName: 'Seumas',
        lastName: 'Joerning',
        email: 'sjoerning1w@cpanel.net',
        gender: 'Male',
    },
    {
        id: 70,
        firstName: 'Yancey',
        lastName: 'Lamminam',
        email: 'ylamminam1x@shinystat.com',
        gender: 'Male',
    },
    {
        id: 71,
        firstName: 'Cesare',
        lastName: 'Durtnal',
        email: 'cdurtnal1y@freewebs.com',
        gender: 'Male',
    },
    {
        id: 72,
        firstName: 'Devin',
        lastName: 'Losel',
        email: 'dlosel1z@bigcartel.com',
        gender: 'Male',
    },
    {
        id: 73,
        firstName: 'Layne',
        lastName: 'Fyfe',
        email: 'lfyfe20@upenn.edu',
        gender: 'Female',
    },
    {
        id: 74,
        firstName: 'Jacintha',
        lastName: 'Gallant',
        email: 'jgallant21@goodreads.com',
        gender: 'Female',
    },
    {
        id: 75,
        firstName: 'John',
        lastName: 'Burnip',
        email: 'jburnip22@opera.com',
        gender: 'Male',
    },
    {
        id: 76,
        firstName: 'Titos',
        lastName: 'Broader',
        email: 'tbroader23@unc.edu',
        gender: 'Male',
    },
    {
        id: 77,
        firstName: 'Allie',
        lastName: 'Lippo',
        email: 'alippo24@google.com',
        gender: 'Male',
    },
    {
        id: 78,
        firstName: 'Dyna',
        lastName: "M'Quharg",
        email: 'dmquharg25@disqus.com',
        gender: 'Female',
    },
    {
        id: 79,
        firstName: 'Yoshi',
        lastName: 'Fayer',
        email: 'yfayer26@cbc.ca',
        gender: 'Female',
    },
    {
        id: 80,
        firstName: 'Leighton',
        lastName: 'Delieu',
        email: 'ldelieu27@cnet.com',
        gender: 'Male',
    },
    {
        id: 81,
        firstName: 'Duffy',
        lastName: 'Noen',
        email: 'dnoen28@state.tx.us',
        gender: 'Male',
    },
    {
        id: 82,
        firstName: 'Corissa',
        lastName: 'Crighton',
        email: 'ccrighton29@usgs.gov',
        gender: 'Female',
    },
    {
        id: 83,
        firstName: 'Kris',
        lastName: 'Anscombe',
        email: 'kanscombe2a@ucla.edu',
        gender: 'Female',
    },
    {
        id: 84,
        firstName: 'Kristy',
        lastName: 'Champneys',
        email: 'kchampneys2b@taobao.com',
        gender: 'Female',
    },
    {
        id: 85,
        firstName: 'Rory',
        lastName: 'Cecchetelli',
        email: 'rcecchetelli2c@yale.edu',
        gender: 'Female',
    },
    {
        id: 86,
        firstName: 'Meggi',
        lastName: 'Wolstencroft',
        email: 'mwolstencroft2d@about.com',
        gender: 'Female',
    },
    {
        id: 87,
        firstName: 'Jim',
        lastName: 'Hilliam',
        email: 'jhilliam2e@upenn.edu',
        gender: 'Male',
    },
    {
        id: 88,
        firstName: 'Leelah',
        lastName: 'Kobke',
        email: 'lkobke2f@shop-pro.jp',
        gender: 'Female',
    },
    {
        id: 89,
        firstName: 'Sile',
        lastName: 'Jopp',
        email: 'sjopp2g@unesco.org',
        gender: 'Female',
    },
    {
        id: 90,
        firstName: 'Geoffry',
        lastName: 'Valentelli',
        email: 'gvalentelli2h@chicagotribune.com',
        gender: 'Male',
    },
    {
        id: 91,
        firstName: 'Keefer',
        lastName: 'Ech',
        email: 'kech2i@dailymail.co.uk',
        gender: 'Male',
    },
    {
        id: 92,
        firstName: 'Hubert',
        lastName: 'Pladen',
        email: 'hpladen2j@weibo.com',
        gender: 'Male',
    },
    {
        id: 93,
        firstName: 'Wheeler',
        lastName: 'McCutheon',
        email: 'wmccutheon2k@guardian.co.uk',
        gender: 'Male',
    },
    {
        id: 94,
        firstName: 'Jessie',
        lastName: 'Coomber',
        email: 'jcoomber2l@google.it',
        gender: 'Male',
    },
    {
        id: 95,
        firstName: 'Isabeau',
        lastName: 'Polon',
        email: 'ipolon2m@auda.org.au',
        gender: 'Female',
    },
    {
        id: 96,
        firstName: 'Karl',
        lastName: 'Sterricks',
        email: 'ksterricks2n@auda.org.au',
        gender: 'Male',
    },
    {
        id: 97,
        firstName: 'Andris',
        lastName: 'MacSkeaghan',
        email: 'amacskeaghan2o@aol.com',
        gender: 'Male',
    },
    {
        id: 98,
        firstName: 'Karee',
        lastName: 'Bartholat',
        email: 'kbartholat2p@oakley.com',
        gender: 'Female',
    },
    {
        id: 99,
        firstName: 'Sandor',
        lastName: 'Bockmann',
        email: 'sbockmann2q@va.gov',
        gender: 'Male',
    },
    {
        id: 100,
        firstName: 'Kirsti',
        lastName: 'Goldsack',
        email: 'kgoldsack2r@archive.org',
        gender: 'Female',
    },
];

export const fakeFetchAsync = (
    pagination: Pagination,
    sortBy: PropertyAccessor<DataItem> | null,
    direction: SortDirection | null
) =>
    new Promise<PagedResult<DataItem>>((resolve) => {
        setTimeout(() => {
            resolve({
                totalCount: data.length,
                items: applyPagination(applySorting(data, sortBy, direction), pagination),
            });
        }, Math.random() * 2000);
    });

export default data;
